# Generated by Django 5.0.6 on 2024-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0002_alter_template_template_alter_template_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetailmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('age', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=20)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(max_length=20)),
                ('skill3', models.CharField(max_length=20)),
                ('skill4', models.CharField(max_length=20)),
                ('skill5', models.CharField(max_length=20)),
                ('skill6', models.CharField(max_length=20)),
                ('education1', models.CharField(max_length=50)),
                ('education2', models.CharField(max_length=50)),
                ('education3', models.CharField(max_length=50)),
                ('institute1', models.CharField(max_length=100)),
                ('institute2', models.CharField(max_length=100)),
                ('institute3', models.CharField(max_length=100)),
                ('experience1', models.CharField(max_length=100)),
                ('experience2', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=100)),
            ],
        ),
    ]
