# Generated by Django 5.0.6 on 2024-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0003_userdetailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailmodel',
            old_name='age',
            new_name='dateofbirth',
        ),
    ]
