# Generated by Django 5.0.6 on 2024-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beforelogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
